prgrms-web-devcourse-final-project/WEB5_6_Code9ine_BE

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/MemberMockController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberEmailSendRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberEmailSendResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberEmailVerifyRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberEmailVerifyResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberGoalRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberGoalResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberLoginRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberLoginResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberLogoutRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberLogoutResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberMypageRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberMypageResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberPasswordFindRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberPasswordFindResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberPasswordResetRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberPasswordResetResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberProfileImageRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberProfileImageResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberSignupRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberSignupResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/config/security/SecurityConfig.java

회원/마이페이지 도메인 전반에 대해 Mock API 구현 및 코드 정비
✨ 회원/인증 기능 Mock API
회원/인증 Mock API 개발
•	회원가입: /api/members/signup
•	로그인: /api/members/login
•	로그아웃: /api/members/logout
•	이메일 인증 코드 발송/검증: /api/members/email/send, /api/members/email/verify
•	비밀번호 찾기/재설정: /api/members/password/find, /api/members/password/reset
•	카카오 소셜 로그인: /api/members/login/kakao
마이페이지/프로필/목표 Mock API 개발
•	마이페이지 조회/수정: /api/members/mypage (GET/PATCH)
•	프로필 이미지 변경: /api/members/profile-image
•	목표 금액 설정: /api/members/mypage/goal
•	회원 탈퇴: /api/members (DELETE)
DTO/컨트롤러/도메인 구조 정비
•	DTO 클래스 도메인별 패키지로 이동
•	컨트롤러 통합: MemberMockController 에서 일괄 관리
📦 공통/구조 정비
각 API별 Request/Response DTO → dto 패키지로 이동
MemberMockController 에서 모든 회원/마이페이지/목표 관련 엔드포인트 관리
SecurityConfig 에서 /api/members/login 접근 허용 추가

feat: 회원/마이페이지 Mock API 구현 및 DTO/구조 정비

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/admin/AdminStatsController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/admin/AdminStoreController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/admin/AdminUsersController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/admin/dto/AdminStatsResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/admin/dto/AdminStoreCreateRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/admin/dto/AdminStoreMenuResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/admin/dto/AdminStoreResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/admin/dto/AdminStoreUpdateRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/admin/dto/AdminUserResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/response/ApiResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/response/ResponseCode.java

관리자 도메인의 Mock API 및 DTO 구현
✨ 관리자 기능 Mock API
- 관리자 모든 회원 조회 : (GET) /api/admin-users
- 관리자 유저 닉네임으로 유저 검색 : (GET) /api/admin-users/search?nickname={nickname}
- 관리자 유저 차단 : (PATCH) /api/admin-users/{user-id}/block
- 관리자 모든 장소 조회 : (GET) /api/admin-stores
- 관리자 카테고리별 장소 조회 : (GET) /api/admin-stores/search?category={category}
- 관리자 장소 등록 : (POST) /api/admin-stores
- 관리자 장소 수정 : (PATCH) /api/admin-stores/{store-id}
- 관리자 장소 삭제 : (PATCH) /api/admin-stores/{store-id}/delete
- 관리자 당일 통계 조회 : (GET) /api/admin-stats/daily-stats
📦 공통/구조 정비
- API 별로 필요한 dto 정의
- 관리자 회원 관리, 장소 관리, 통계 조회로 컨트롤러 분할

feat: 관리자 Mock API 및 DTO 구현

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/admin/AdminStoreController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/community/CommunityController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/dto/CommunityCommentCreateRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/dto/CommunityCommentResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/dto/CommunityPostCreateRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/dto/CommunityPostDetailResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/dto/CommunityPostUpdateRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/dto/CommunityTopPostResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/dto/CommunityUserInfoResponse.java

커뮤니티 도메인의 Mock API 및 DTO 구현
✨ 커뮤니티 기능 Mock API
- 커뮤니티 로그인 유저 정보 : (GET) /api/community/me
- 커뮤니티 게시글 카테고리별 조회 : (GET) /api/community/posts?category={category}
- 커뮤니티 게시글 생성 : (POST) /api/community/posts
- 커뮤니티 게시글 수정 : (PATCH) /api/community/posts/{post-id}
- 커뮤니티 게시글 삭제 : (PATCH) /api/community/posts/{post-id}/delete
- 커뮤니티 게시글별 댓글 조회 : (GET) /api/community/posts/{post-id}/comments
- 커뮤니티 게시글 댓글 작성 : (POST) /api/community/posts/{post-id}/comments
- 커뮤니티 게시글 댓글 삭제 : (PATCH) /api/community/comments/{comment-id}/delete
- 커뮤니티 게시글 좋아요 활성화/비활성화 : (PATCH) /api/community/posts/{post-id}/like
- 커뮤니티 게시글 북마크 활성화/비활성화 : (PATCH) /api/community/posts/{post-id}/bookmark
- 커뮤니티 인기 게시글 조회 : (GET) /api/community/posts/top
📦 공통/구조 정비
- API 별로 필요한 dto 정의

Feat : 커뮤니티 Mock API 및 DTO 구현

---

apimocking-main/apimocking-boilerplate/.gitignore
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/auth/jwt/TokenCookieFactory.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/config/WebConfig.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/config/security/SecurityConfig.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/config/security/SecurityConfigMock.java

1. 로그인 DTO 및 Swagger 예시 개선
- 로그인 요청 DTO(LoginRequest) 필드명을 email로 명확히 유지
- Swagger 문서에서 Request Body 예시가 username이 아니라 email로 노출되도록 @Schema 어노테이션 추가
2. 로그인 입력값 디버깅 로그 추가
- 로그인 시도 시 입력값(email, password)을 콘솔에 출력하는 로그 추가
3. 토큰 쿠키 전송 설정 수정
4. 기타
- 불필요한 mock 컨트롤러/설정 정리

feat: [회원가입/로그인] 로그인 DTO 및 Swagger 예시 개선

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/auth/domain/Principal.java

Principal.createPrincipal에서 subject로 memberId 대신 email 사용
- JWT 토큰의 subject가 항상 이메일이 되도록 수정
- UserDetailsServiceImpl, 인증 처리 전반이 이메일 기준으로 일관되게 동작
- 인증이 필요한 API 호출 시 500 에러(UsernameNotFoundException) 발생 문제 해결

fix: JWT subject 및 인증 기준을 memberId에서 email로 일원화

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/mock/member/MemberMockController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/mock/notification/NotificationMockController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/domain/Member.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/notification/domain/Notification.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/notification/model/NotificationDTO.java

DB/엔티티 변경
- notification 테이블에 senderId(int, NOT NULL) 필드 추가
- notification 테이블에 type(varchar(255), NULL 허용) 필드 추가
- Notification 엔티티와 NotificationDTO에 해당 필드 매핑 추가
API 응답 변경
- NotificationMockController에서 mock 응답에 senderId, type 필드 포함
- 예시 데이터에 senderId=2, type="NOTICE" 및 senderId=3, type="LIKE" 추가

feat: notification 테이블에 senderId, type 필드 추가

---

apimocking-main/apimocking-boilerplate/pom.xml
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/EmailVerificationController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/mock/member/MemberMockController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/achieved_title/domain/AchievedTitle.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/auth/domain/EmailVerification.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/auth/repos/EmailVerificationRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/auth/service/EmailCleanupScheduler.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/auth/service/EmailService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/auth/service/EmailVerificationService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/domain/Member.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/auth/jwt/filter/JwtAuthenticationFilter.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/config/security/SecurityConfig.java

- **Member 연관관계 추가**: `@ManyToOne(fetch = FetchType.LAZY) @JoinColumn(name = "member_id")`
- **회원별 칭호 관리**: 각 칭호 레코드가 어떤 회원이 달성했는지 명확히 저장
- **데이터 무결성**: `nullable = false`로 회원 정보 필수화
- **외래키 제약**: Member 테이블의 member_id 참조
- **관계**: 1명의 회원이 여러 칭호 달성 가능 (1:N)
- **회원별 칭호 조회**: 특정 회원이 달성한 모든 칭호 조회 가능
- **마이페이지 연동**: 달성한 칭호 목록과 장착한 칭호 구분 표출
- **칭호 달성 추적**: 회원별 칭호 달성 이력 관리
- 기존 ChallengeCount와는 별도로 실제 달성한 칭호를 관리
- 마이페이지에서 회원별 달성 칭호 목록 표출 가능
- 칭호 달성 조건 충족 시 AchievedTitle 레코드 생성

feat: AchievedTitle 엔티티에 Member 연관관계 추가

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/mock/member/MemberMockController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/auth/service/EmailService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/repos/MemberRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/config/security/SecurityConfig.java

- **엔드포인트:** `POST /api/users/email/find`
- **기능:** 이름과 휴대폰번호로 이메일 조회
- **특징:**
- 동일한 이름으로 여러 계정이 존재할 경우 모두 반환
- 보안을 위한 이메일 마스킹 처리 (예: `te****@test.com`)
- 휴대폰번호 형식 검증 추가
- **엔드포인트:** `POST /api/users/password/find`
- **기능:** 임시 비밀번호를 이메일로 발송
- **특징:**
- 8자리 랜덤 임시 비밀번호 생성
- 이메일 발송 실패 처리
- 비밀번호 정책 검증 (8자 이상, 영문/숫자/특수문자 포함)
- **엔드포인트:** `PATCH /api/users/password`
- **기능:** JWT 토큰 기반 현재 사용자 비밀번호 변경
- **특징:**
- 기존 비밀번호 확인 후 변경
- 새 비밀번호 정책 검증
- JWT 토큰에서 사용자 정보 추출
- **기존:** `010-1234-5678` (하이픈 포함)
- **변경:** `01012345678` (하이픈 제거)
- **적용 범위:** 회원가입, 아이디 찾기
- **정규식:** `^01[016789]\\d{7,8}$`
- **SecurityConfig:** 아이디 찾기, 비밀번호 찾기 API를 `permitAll()`로 설정
- **인증 없이 접근 가능:** `/api/users/email/find`, `/api/users/password/find`
- 모든 필드에 `@NotBlank`, `@Email`, `@Pattern` 검증 추가
- 휴대폰번호 정규식 통일
- 비밀번호 정책 …

feat: 아이디/비밀번호 찾기 기능 구현 및 휴대폰번호 형식 통일

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/model/MemberDTO.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/repos/MemberRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/service/MemberService.java

- **소셜 로그인 식별자 구조 개선**
- 기존 provider/providerId(소셜 타입/고유ID) → kakaoId(카카오 고유ID) 단일 필드로 통합
- Member, MemberDTO, MemberRepository, MemberService 등 모든 계층에서 kakaoId만 사용하도록 일괄 변경
- get/setProvider, get/setProviderId, get/setSocialEmail 등 관련 메서드/로직 완전 제거
- **DB 및 서비스 로직 정비**
- 카카오 로그인 회원은 kakaoId로만 식별 및 가입/로그인 처리
- 이메일 미제공 케이스도 정상 처리 가능
- 소셜 로그인 구조를 단순화하여 유지보수성 및 확장성 향상
- provider/providerId 조합 대신 kakaoId 단일 필드로 회원 식별
- 관련된 모든 매핑/조회/저장/로직을 kakaoId 기준으로 통일
**이슈: 카카오 로그인 회원 식별 및 관리 구조 단순화**

refactor: 소셜 로그인 식별자 provider/providerId → kakaoId 단일 필드로 일괄 변경

---

apimocking-main/apimocking-boilerplate/pom.xml
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/community/CommunityController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget/service/BudgetService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/repos/CommunityBookmarkRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/repos/CommunityRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/service/CommunityService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/service/CommunityServiceImpl.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/festival/domain/Festival.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/invite_code/domain/InviteCode.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/invite_code/repos/InviteCodeRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/invite_code/service/InviteCodeService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/library/domain/Library.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/domain/Member.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/service/MemberService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/notification/domain/Notification.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/place_bookmark/domain/PlaceBookmark.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/place_bookmark/repos/PlaceBookmarkRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/place_bookmark/service/PlaceBookmarkService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/store/domain/Store.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/entity/BaseEntity.java

**마이페이지 기능 구현**
- 마이페이지 조회 API 구현
- 마이페이지 프로필 수정 API 구현
- 목표 설정/조회 API 구현
- 마이페이지 목표 달성률 계산 로직 구현 및 Decimal 타입을 BigDecimal로 변경
**칭호 시스템**
- 칭호 관련 API 구현
**커뮤니티 기능**
- 내가 작성한 게시글 조회 API 구현
**장소 관리**
- 장소 북마크 조회/해제 API 구현
**회원 관리 기능**
- 회원 탈퇴 API 구현
- 초대코드 생성 및 회원가입 시 초대코드 입력 기능 구현
- 타입 안정성: Decimal 타입을 BigDecimal로 변경하여 금융 데이터의 정확한 계산 보장

feat: 마이페이지 및 회원 관리 기능 구현

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/budgetdetail/BudgetDetailController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/challengeController/ChallengeController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget_detail/service/BudgetDetailService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge/domain/Challenge.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge/model/ChallengeStatusDto.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge/repos/ChallengeRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge/service/ChallengeService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge_count/domain/ChallengeCount.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge_count/repos/ChallengeCountRepository.java

📋 구현 내용
1. 챌린지전체조회 (GET) /api/challenge
전체조회할 때 15개의 챌린지 대해서 나오고 사용자의 행동에 따라 바뀌는 progress가 반영되어서 조회됩니다.
일일챌린지는 Challenge_count테이블의 당일날짜 progress
월별챌린지는 당일 월의 progress
커뮤니티 챌린지는 단발성이라 날짜관련없이 지금까지의 progress가 나옵니다.
2. 만원의 행복 챌린지 budgetdetailService에 handel_under10000Challenge메서드를 추가해서 가계부내역 추가,수정,삭제시 progress가
반영되도록 하였습니다. 
챌린지 추가
INSERT INTO challenge (challenge_id, name, type, description, exp, icon, total) VALUES
(1, '만원의 행복', '일일', '만원으로 하루 살아보기', 20, 'moneyIcon', 1),
(2, '찐 기록러', '일일', '오늘 사용한 영수증 인증하기', 20, 'receipt', 1),
(3, '소비 단식러', '일일', '하루 식비 0원 달성', 20, 'zeroFood', 1),
(4, '강철 다리', '일일', '하루 교통비 0원 달성', 20, 'zeroTransition', 1),
(5, '소통왕', '월간', '댓글, 좋아요 10개', 100, 'heart', 10),
(6, '개근왕', '월간', '한 달 출석 체크', 100, 'oneMonth', 30),
(7, '인싸왕', '월간', '친구 초대 이벤트', 100, 'friend', 1), …

Feature: 챌린지 전체조회, 만원의 행복 챌린지

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/budgetdetail/BudgetDetailController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/challengeController/ChallengeController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget/repos/BudgetRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget_detail/repos/BudgetDetailRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget_detail/service/BudgetDetailService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge/domain/Challenge.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge/model/ChallengeStatusDto.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge/repos/ChallengeRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge/service/ChallengeService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge_count/domain/ChallengeCount.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge_count/repos/ChallengeCountRepository.java

📋 구현 내용
1. 소비단식러챌린지 성공기준 (progress =1)
1. 오늘 가계부의 카테고리에 식비가 없을 시
2. 오늘 가계부를 지출없음으로 등록시
2. 소비단식러챌린지 실패기준 ( progress = 0)
1. 오늘 가계부의 카테고리에 식비가 있을 시
2. 오늘 가계부를 아예 작성 안 했을 시 ( 가계부를 작성했다가 모든내역을 삭제하거나, 다른날짜로 수정을해서 당일  
가계부에 내역이 없는상태가 된다면 가계부 작성 안 한것으로 처리) 
3. 강철다리챌린지 성공기준 (progress =1)
1. 오늘 가계부의 카테고리에 교통비가 없을 시
2. 오늘 가계부를 지출없음으로 등록시
4. 강철다리챌린지 실패기준 ( progress = 0)
1. 오늘 가계부의 교통비에 식비가 있을 시
2. 오늘 가계부를 아예 작성 안 했을 시 ( 가계부를 작성했다가 모든내역을 삭제하거나, 다른날짜로 수정을해서 당일  
가계부에 내역이 없는상태가 된다면 가계부 작성 안 한것으로 처리) 
5. 챌린지 전체 조회시 ApiResponse로 응답
6. 지출없음 등록시 챌린지 반영되게 수정

Feature: 소비단식러,강철다리 챌린지

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/attendance/repos/AttendanceRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/auth/AuthService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget/model/BudgetDaySummary.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget/repos/BudgetRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget/service/BudgetCalendarService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget_detail/repos/BudgetDetailRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget_detail/service/BudgetDetailService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge/service/ChallengeService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge_count/repos/ChallengeCountRepository.java

📋 구현 내용
개근왕챌린지(progress =1~30) -> 30이되면 성공
1. 출석하면 Attendance테이블에서 확인 후 progress수정
머니 매니저챌린지  ( progress = 1)
1. 이번 달 수입인 내역이 있으면 성공
기록장인 챌린지 (progress =1~30) -> 30이 되면 성공,  등록시 되고 수정삭제해서 가계부가 없어도 그 날 가계부작성한것으로 처리됨.. 수정필요하면 수정
1. 가계부 작성을 연속으로 했을 때 progress+1 
절약왕 챌린지 ( progress = 1)
1. 이번달 지출이 저번달 보다 적으면 성공

Feature: 개근왕, 머니 매니저, 기록장인, 절약왕챌린지

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/achieved_title/domain/AchievedTitle.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/achieved_title/repos/AchievedTitleRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget_detail/repos/BudgetDetailRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget_detail/service/BudgetDetailService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge/service/ChallengeService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge_count/repos/ChallengeCountRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/notification/repos/NotificationRepository.java

📋 **구현 내용**
1. 스케줄러를 활용해서 칭호획득 시 알림이 가게하였습니다. 
- 일일챌린지같은경우
오늘이 7월22일이면 7월23일 00시00분00초가 됐을 때 7월22일의 일일챌린지의 달성여부를 판단해서 
성공한 챌린지만 "○○○칭호 획득하였습니다" 라는 알림이가게되고 AchievedTitle테이블에 추가됩니다
혹시 달성한 칭호가 있다면 count+1 하도록 구현
- 월간챌린지같은경우 
8월1일 00시00분00초가 되면 7월의 챌린지의 달성여부를 판단해서 일일챌린지와 마찬가지로 알림이 갑니다
2. AchievedTitle에 icon컬럼 추가하고 GenerationType.IDENTITY로 수정.
3. 일일미션은 자정에 알림, 월간도 매달1일에 알림이가는데 "머니 매니저"챌린지는 수입을 등록하자마자 알림이가고 칭호획득
**유의사항**
알림이 가는지 안 가는지 확인할 때 자정이나 다음달1일이 되야 확인할 수 있는데 ChallengeService에 주석처리된 스케줄러 사용하면 매 분 알림이 가도록 변경해서 확인할 수 있습니다 
월간 챌린지 같은경우는 저번달의 챌린지 데이터가 ChallengeCount에 있어야하고 일일챌린지도 어제의 챌린지 데이터가 있어야합니다

Feature: 챌린지 칭호획득 알림기능

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/config/WebConfig.java

1. **비밀번호 찾기(임시 비밀번호 발급) API 500 에러 해결**
- PasswordFindResponse DTO에 message 필드를 추가하여 Jackson 직렬화 오류(500 Internal Server Error) 해결
- 임시 비밀번호 발급/이메일 발송 후 정상적으로 성공 메시지 응답 반환
- 프론트엔드에서 비밀번호 찾기 결과를 안정적으로 받을 수 있음
2. **CORS 설정(credentials: 'include' 대응) 개선**
- allowedOrigins를 'http://localhost:3000'으로 명시적으로 지정
- allowCredentials 옵션을 true로 변경
- 모든 HTTP 메서드 및 헤더 허용 유지
- 프론트엔드에서 credentials: 'include' 옵션 사용 시 CORS 오류 없이 인증 쿠키가 정상적으로 전송됨

비밀번호 찾기 API 직렬화 오류 및 CORS credentials 설정 개선

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/auth/jwt/JwtTokenProvider.java

- /api/members/token/refresh 엔드포인트 추가 (POST)
- refreshToken을 받아 새 accessToken/refreshToken을 발급 및 쿠키로도 반환
- JwtTokenProvider에 getJtiFromToken, getUsername, getRoles 메서드 추가

feat: 리프레시 토큰으로 엑세스 토큰 재발급 API 구현

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/geminichatbot/GeminiChatbotController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/geminichatbot/repos/GeminiChatbotBudgetDetailRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/geminichatbot/service/GeminiChatbotService.java

- /api/geminichatbot/analyze 엔드포인트 신설 (POST, 인증 필요)
- 로그인 사용자의 최근 한달간 지출 상세내역을 DB에서 자동 조회
- BudgetDetail에서 날짜/카테고리/금액 단위로 프롬프트 생성 후 Gemini API 호출
- Gemini 응답을 { "message": ... } 형태로 반환 (예외 시 동일 포맷)
- 요청 바디 없이 인증 정보만으로 동작

feat: Gemini 기반 자산관리 챗봇 API 구현 (최근 한달 지출 내역 자동 분석)

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/geminichatbot/GeminiChatbotController.java

- 응답 구조를 message1,2,3에서 spendingPattern, savingFeedback, spendingTips 으로 직관적이게 네이밍 변경
- 사용자별 하루 최대 3회 요청 제한 기능 구현
- 프롬프트 개선으로 각 항목별 명확한 구분 요청
- 에러 응답도 동일한 구조로 통일

feat: Gemini 챗봇 API 응답 구조 개선 및 요청 제한 기능 추가

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/place_bookmark/service/PlaceBookmarkService.java

- storeId, festivalId, libraryId, placeId를 String에서 Long 타입으로 통일

fix: 북마크한 장소 조회 API 응답에서 ID 필드 타입을 String에서 Long으로 변경

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/geminichatbot/GeminiChatbotController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/notification/NotificationController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/geminichatbot/repos/GeminiChatbotBudgetDetailRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/geminichatbot/service/GeminiChatbotService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/notification/service/NotificationService.java

칭호 획득 알림 API 응답에 획득한 칭호의 aTId 를 추가
- `TitleNotificationResponse` DTO에 `aTId` 필드 추가
- `senderId` 필드를 활용하여 `aTId` 정보 전달
- TITLE 타입 알림에서 `senderId`에 `aTId` 저장
- TITLE 타입 알림 생성 시 `senderId`에 `aTId` 전달
- 다른 타입(LIKE, COMMENT)은 기존대로 실제 발신자 ID 사용

 feat: 칭호 획득 알림 응답에 aTId 필드 추가

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/mock/member/MemberMockController.java

- JwtAuthenticationFilter에서 자동 토큰 갱신 처리로 인해 수동 API 불필요
- MemberController에서 /api/members/token/refresh 엔드포인트 제거
- TokenRefreshResponse, MemberTokenRefreshRequest DTO 클래스 제거

refactor: 불필요한 토큰 재발급 API 제거

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/EmailVerificationController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/OAuth2SignupController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/notification/NotificationController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/notification/repos/NotificationRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/notification/service/NotificationService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/response/ResponseCode.java

- Member, EmailVerification, OAuth2Signup 컨트롤러의 예외 처리 통일
- ResponseEntity 직접 반환 → CommonException 던지기로 변경
- 회원 관련 구체적인 ResponseCode 추가
- @ExceptionHandler를 통한 중앙화된 예외 처리로 일관성 확보

refactor: 컨트롤러 예외 처리 통일 및 ResponseCode 추가
