apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/budget/BudgetController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget/model/BudgetAnalyzeResponseDto.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget/model/BudgetCalenderResponseDto.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget/model/BudgetCategorySummary.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget/model/BudgetDaySummary.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget/model/BudgetGoal.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget/model/BudgetMonthlyExpense.java

가계부 도메인의 Mock API 및 DTO 구현
✨ 가계부 기능 Mock API
가계부 달력페이지: (GET) /api/budget/calendar
가계부 분석페이지: (GET) /api/budget/analyze
API 별로 필요한 dto 정의

Feat: MockApi budget(달력,분석페이지) 및 Dto 구현

---

apimocking-main/apimocking-boilerplate/pom.xml
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/admin/AdminStoreController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/admin/AdminUsersController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/community/CommunityController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/dto/CommunityCommentCreateRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/dto/CommunityCommentResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/dto/CommunityPostCreateRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/dto/CommunityPostDetailResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/dto/CommunityPostUpdateRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/dto/CommunityTopPostResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/community/dto/CommunityUserInfoResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/payload/PageParam.java

관리자, 커뮤니티 도메인의 Mock API 및 DTO 수정
✨ 관리자, 커뮤니티 기능 Mock API
- 페이지네이션이 필요한 부분들은 페이지네이션 처리 
- 커뮤니티 게시글 카테고리별 조회 : (GET) /api/community/posts?category={category}?page={page}&size={size}
- 관리자 모든 회원 조회 : (GET) /api/admin-users?page={page}&size={size}
- 관리자 모든 장소 조회 : (GET) /api/admin-stores?page={page}&size={size}
- 관리자 카테고리별 장소 조회 : (GET) /api/admin-stores/search?category={category}&page={page}&size={size}
📦 공통/구조 정비
- 더미데이터 추가
- 커뮤니티 dto 필드값 추가

Refactor: 페이지네이션 추가, dto 수정

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/searchPlace/SearchPlaceController.java

store 강제처리
카테고리별 모든 경우의 수 고려해서 다시 설계했습니다

Refactor: search and detail Refactor

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/mock/searchPlace/SearchPlaceMockController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/mock/userMain/UserMainMockController.java

클래스 이름에 mock 추가
@Profile 어노테이션 추가

Refactor: Profile(mock)추가 및 class 이름 mock 추가

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/library/domain/Library.java

Library 엔티티 contact 빠진거 추가했습니다.

Refactor: Library엔티티 수정

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget/domain/Budget.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget_detail/service/BudgetDetailService.java

📋 구현 내용
1. 가계부 내역 생성 시 totalIncome, totalExpense 가 수정됩니다
2. 가계부 내역 수정 시 totalIncome, totalExpense 가 수정됩니다
3. 가계부 내역 삭제 시 totalIncome, totalExpense 가 수정됩니다

Feat: 가계부 total값 변경기능

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/notification/NotificationController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/notification/service/NotificationService.java

- NotificationCreateRequest DTO 추가
- 빌더 패턴을 위한 정적 팩토리 메서드 제공
- createNotification 메서드 파라미터 단순화
- 컨트롤러에서 DTO 변환 로직 추가

refactor: NotificationCreateRequest DTO 도입으로 파라미터 정리

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/mock/searchPlace/SearchPlaceMockController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/placesbookmark/PlacesBookmarkController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/festival/model/DetailFestivalPlaceResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/festival/repos/FestivalRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/library/model/DetailLibraryPlaceResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/library/repos/LibraryRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/place_bookmark/domain/PlaceBookmark.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/place_bookmark/model/BookmarkResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/place_bookmark/model/BookmarkToggleRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/place_bookmark/repos/PlaceBookmarkRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/place_bookmark/service/PlaceBookmarkService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/store/dto/BookmarkToggleMockRequest.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/store/dto/DetailPlaceResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/store/dto/DetailStorePlaceResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/store/repos/StoreRepository.java

Feat: 북마크 기능구현
Refactor: 식당 상세정보 type값 담아보내기

Feat: 북마크 기능구현, Refactor: 식당 상세정보 type값 담아보내기 수정

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge_count/model/ChallengeTopResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge_count/repos/ChallengeCountRepository.java

Refactor: 메인페이지 챌린지 description 조회로 수정

Refactor: 메인페이지 챌린지 description 조회로 수정

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/config/security/SecurityConfig.java

Refactor: mainpage security permitAll
메인페이지 api perminAll 처리해뒀습니다

Refactor: mainpage security permitAll

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/admin/AdminStoreController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/admin/AdminUserController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/admin/dto/AdminStoreListResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/admin/dto/AdminUserListResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/admin/service/AdminStoreService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/admin/service/AdminStoreServiceImpl.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/admin/service/AdminUserService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/admin/service/AdminUserServiceImpl.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/repos/MemberRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/store/repos/StoreRepository.java

✨ 관리자 유저, 장소 조회 리팩토링
- 페이지네이션 제거 후 응답에 총 데이터 개수 필드 추가
📦 공통/구조 정비
- 총 데이터 개수와 유저, 장소 리스트로 구성된 dto 추가

refactor : 관리자 유저, 장소 조회

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/s3/S3PresignedUrlController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/auth/jwt/filter/JwtAuthenticationFilter.java

로그아웃 성공 시 200 OK 가 아닌 401 에러가 발생하는 현상 수정

fix: 로그아웃 성공 시 401이 아닌 200 OK와 정상 메시지 반환

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/config/security/SecurityConfig.java

Refactor: 검색 security 수정
"/api/searches/top","/api/places/search","/api/places/detail"
permitAll 로 열어놨습니다

Refactor: 검색 security 수정

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/auth/jwt/TokenCookieFactory.java

쿠키 설정을 SameSite=None으로 변경하여 크로스 사이트 요청 허용 (개발 환경용 Secure=false)

fix: 쿠키 설정을 SameSite=None으로 변경하여 크로스 사이트 요청 허용 (개발 환경용 Secure=false)

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/place_bookmark/service/PlaceBookmarkService.java

Refactor: Lazy 문제 해결
{
"code": "0000",
"message": "정상적으로 완료되었습니다.",
"data": [
{
"firstprice": 9000,
"thirdmenu": null,
"address": "서울특별시 종로구 종로53길 7-2",
"placeId": "2",
"storeId": "2",
"type": "store",
"secondprice": 15000,
"firstmenu": "생고기김치찌개",
"contact": "02-765-1298",
"name": "만족김치삼겹살",
"thirdprice": null,
"category": "한식",
"bookmarkedAt": "2025-07-24T12:24:52.159166",
"secondmenu": "삽겹살(180g)"
},
{
"firstprice": 13000,
"thirdmenu": null,
"address": "서울특별시 종로구 수표로 117 (낙원동)",
"placeId": "3",
"storeId": "3",
"type": "store",
"secondprice": 7000,
"firstmenu": "삼계탕",
"contact": "02-3673-1239",
"name": "먹고갈래지고갈래",
"thirdprice": null,
"category": "한식",
"bookmarkedAt": "2025-07-24T12:24:56.699495",
"secondmenu": "산채비빔밥"
},
{
"firstprice": 7000,
"thirdmenu": null,
"address": "서울특별시 종로구 동숭길 …

Refactor: Lazy 문제 해결

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/auth/AuthService.java

feat: 프로필 수정 API 통합 및 비밀번호/프로필 이미지 변경 API 삭제

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/geminichatbot/GeminiChatbotController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/geminichatbot/repos/GeminiChatbotBudgetDetailRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/geminichatbot/service/GeminiChatbotService.java

Gemini 챗봇의 응답 구조를 6개로 확장하고, 전체 사용자 평균과의 구체적인 금액 비교 기능을 추가했습니다.
- **기존**: 3개 응답 (`spendingPattern`, `savingFeedback`, `spendingTips`)
- **변경**: 6개 응답 (`response1` ~ `response6`)
- **새로운 서비스 메서드**: `getAverageSpendingByCategory()`
- **새로운 리포지토리 메서드**: `findAllExpenseDetailsByDateBetween()`
- **카테고리별 평균 지출 계산**: 최근 1개월 전체 사용자 데이터 기반
- **카테고리별 총액 정보 추가**: 개별 지출 내역 + 카테고리별 합계
- **구조화된 데이터**: Gemini가 더 정확한 비교 분석 가능
- **구체적인 금액 비교 요청**: "전체 사용자 평균 식비 지출은 100,000원이고 사용자의 식비 지출액은 150,000원으로 평균보다 50,000원 더 많이 쓰셨어요" 형태의 응답 요청
- **6개 질문 명시**: 각 질문에 대한 구체적인 답변 요구사항 추가
1. 내가 제일 돈 많이 쓰는 건 어떤 분야 같니?
2. 내 수입보다 많이 지출한 분야 뭐야?
3. **다른 사람들보다 내가 많이 쓴 분야는 뭐야?** (전체 사용자 평균과 구체적 비교)
4. 절약 꿀팁이 뭐가 있어?
5. 소비에서 절약할 수 있는 카테고리는 뭐야?
6. 내가 어디서 돈을 아낄 수 있을 것 같니?
- `GeminiChatbotController.java`: 응답 구조 및 프롬프트 수정
- …

feat: Gemini 챗봇 응답 구조 개선 및 전체 사용자 평균 비교 기능 추가

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge/service/ChallengeService.java

수정사항
- 알림에 AchievedTitle Id를 넘길 수 있도록 수정

refactor : 챌린지 알림 변경

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/achieved_title/repos/AchievedTitleRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/challenge/service/ChallengeService.java

📋 **수정 내용**
알림의 senderid에 atid들어가게 수정하였습니다

fix: 일일,월간챌린지알림수정

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/budgetdetail/BudgetDetailController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/config/CorsConfig.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/infra/config/security/SecurityConfig.java

- BudgetDetailController에서 UserDetails를 Principal로 변경
- 인증 방식 불일치로 인한 배포 환경 500 에러 해결

fix: 가계부 API 인증 방식 통일로 배포 환경 오류 해결

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/dto/MemberWithdrawResponse.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/repos/MemberRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/member/service/MemberService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/notification/service/NotificationService.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/place_bookmark/repos/PlaceBookmarkRepository.java
apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/place_bookmark/service/PlaceBookmarkService.java

feat: 회원탈퇴 후 자동 로그아웃 및 이메일 재사용 기능 구현

---

apimocking-main/apimocking-boilerplate/src/main/java/com/grepp/spring/app/model/budget_detail/service/BudgetDetailService.java

📋 수정 내용
카테고리 교통비 -> 교통으로 수정했습니다

fix: 강철다리 챌린지 수정
